Megadeth/Prim.hs: tweak for ghc-8
ghc-8's template-haskell-2.11 added support for
Kind polymorphism. That led to addition of Kind
field in constructor which causes build failures:

  Megadeth/Prim.hs:146:29: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ _ _ constructors _

Change introduces CPP macro to get support for
both ghc-7.10 and and ghc-8.

Signed-off-by: Sergei Trofimovich <siarheit@google.com>